{% set name = "Flask-Cors" %}
{% set pname = "flask_cors" %}
{% set version = "4.0.0" %}

package:
  name: {{ pname|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f268522fcb2f73e2ecdde1ef45e2fd5c71cc48fe03cffb4b441c6d1b40684eb0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - flask >=0.9
    - six

test:
  imports:
    - flask_cors

about:
  license: MIT
  home: https://github.com/corydolphin/flask-cors
  license_file: LICENSE
  license_family: MIT
  summary: Cross Origin Resource Sharing ( CORS ) support for Flask

  description: |
    A Flask extension for handling Cross Origin Resource Sharing (CORS), making cross-origin AJAX possible.
  doc_url: http://flask-cors.corydolphin.com/en/latest/
  dev_url: https://github.com/corydolphin/flask-cors

extra:
  recipe-maintainers:
    - knaaptime
